### ISSUE TITLE
Not highlighting properly if extra brackets are used in regex

### ISSUE THREAD

**Issue by fenilgmehta** [mbornet-hl/hl#20]
As it can be seen in the below image, using extra circular brackets `()` causes `hl` to not highlight the text as required.

![image](https://user-images.githubusercontent.com/42742240/124113772-726c3180-da89-11eb-8a6e-6a26553bd93a.png)

**Comment by mbornet-hl** [comment]
Hello,
thank you for your message.

First of all, saying hello, please or goodbye is not forbidden none useless, you are not talking to a machine.

Regarding what you consider a problem, it works in fact exactly as intended : **hl** is not **grep** nor **egrep**.
Since one may want to colorize a string in a specific context without colorizing the context, the solution is to enclose the string one want to colorize in parentheses. If you also want to colorize the context, you just have to also enclose the context in parentheses, like this : 

echo '((<=foobar <=foo bar' | hl -e3r '((<=foo)bar)'

which is not useful in this example since everything you specify is colorized and you have no obligation to use any parentheses at all. But that's the way to do when you use extended regular expressions using parentheses and '|' (for OR) and want to colorize the whole string.

For example, if you want to colorize the strings **AB** and **CD**, but only when they are immediately followed by **EF**, and you don't want to colorize **EF**, you will use the following syntax : 

hl -e -3r '(AB|CD)EF'

If you also want to colorize **EF**, you will use : 

hl -e -3r '((AB|CD)EF)'

Kind regards.

**Comment by fenilgmehta** [comment]
Hi,

Thanks a lot for your help and sorry for the direct message which I wrote due to lack of knowledge regarding the usage of GitHub issues.

Kind regards.
