### ISSUE TITLE
add fucntions

### ISSUE THREAD

**Issue by dwizzdonowin** [mbornet-hl/hl#3]
You can add a parameter file hl.hlrc with functions (in replacement of the specfic tree in the PATH.
For exemple the command netstat

netstat(){
if [ $# -gt 0 ]
then
 param=$*
else
 param=" "
fi
exec=`which netstat`
$exec $param  | hl --netstat
}

**Comment by mbornet-hl** [comment]
Sorry, but you cannot use $*.
First of all, you should use $@, and more precisely "$@" (enclosed in double quotes), but anyway you cannot assign "$@" to a variable without changing the number of arguments.
Secondly, the aim of the hl_generic script is to be generic to all command you want to colorize, which means you don't have the modify any script nor write new code.
When you want to colorize a new command, you have two things to do :  
1. define the "new_command" configuration in the ".hl.cfg" file,
2. cd hl_bin; ln hl_generic new_command
and eventually :
hash -d new_command

**Comment by dwizzdonowin** [comment]
You can use shell function a the place of the hl_bin. In my environment, the PATH is modified between the projects so you can't use the hl_bin easily. The shell  function is another solution and you can use the $* it's working.(i have test it and it work well)

**Comment by mbornet-hl** [comment]
Hello,
if you want to use shell functions instead of using hard links to hl_generic in hl_bin, it's up to you : you can you whatever you want if it suits your needs.
Regarding the use of $*, I strongly suggest you read carefully the man page of the shell, and understand well the meaning of $*, $@, "$*" and "$@". In the example you are talking about, it will probably work without any problem with every argument you pass to the script, but if you get used to using $* in your scripts, sooner or later you will encounter problems, especially if the arguments passed to your scripts contain spaces or tabs. Be aware of what others (bad guys, for example) could pass to your scripts, or you could introduce severe security problems. Using $* is not the good writing way to make robust scripts.
